-- 20 categories first
INSERT INTO CATEGORY (CATEGORY_NAME, PARENT_CATEGORY_ID_CATEGORY)
SELECT
  CONCAT('Category ', X),
  CASE 
    WHEN X <= 5 THEN NULL
    ELSE CAST(RAND()*5 + 1 AS INT)
  END
FROM SYSTEM_RANGE(1,20);

-- 70 authors second
INSERT INTO AUTHOR (NAME, AGE, NATIONALITY)
SELECT
  CONCAT('Author ', X),
  CAST(25 + RAND()*50 AS INT),
  CASE 
    WHEN MOD(X,5)=0 THEN 'Algerian'
    WHEN MOD(X,5)=1 THEN 'French'
    WHEN MOD(X,5)=2 THEN 'English'
    WHEN MOD(X,5)=3 THEN 'Moroccan'
    ELSE 'Tunisian'
  END
FROM SYSTEM_RANGE(1,70);

-- 170 books last
INSERT INTO BOOK (TITLE, PUBLICATION_YEAR, LANGUAGE, B_PAGES, CATEGORY_ID_CATEGORY, AUTHOR_ID_AUTHOR)
SELECT
  CONCAT('Book ', X),
  1990 + MOD(X, 35),
  CASE 
    WHEN MOD(X,3)=0 THEN 'English'
    WHEN MOD(X,3)=1 THEN 'French'
    ELSE 'Arabic'
  END,
  100 + MOD(X, 400),
  (SELECT ID_CATEGORY FROM CATEGORY ORDER BY RAND() LIMIT 1),
  (SELECT ID_AUTHOR FROM AUTHOR ORDER BY RAND() LIMIT 1)
FROM SYSTEM_RANGE(1,170);
